---
title: "Remove legend from ggplot2 plot"
author: "Pietro Delfino"
date: "`r format (Sys.Date())`"
tags:
- R coding
- ggplot
- statistics
categories: R, stats, ggplot
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Since I googled it about thousands of times, I post it here to help me stick it into my mind.

To completely remove the legend from a `ggplot2` graph, use this:

`theme(legend.position = 'none')`

If in your plot you are using a different theme from the default one, place the above code after the code for the theme, otherwise it will be replaced.

```{r, dev='svg'}
library(tidyverse)

iris %>%
    ggplot(aes(Species, Sepal.Length, col = Species)) + 
    geom_boxplot()

# remove legend
iris %>%
    ggplot(aes(Species, Sepal.Length, col = Species)) + 
    geom_boxplot() +
    theme(legend.position = 'none')

# if you use a different theme, place `theme(legend.position = 'none')` after the selected theme
iris %>%
    ggplot(aes(Species, Sepal.Length, col = Species)) + 
    geom_boxplot() +
    theme_bw() +
    theme(legend.position = 'none')
```


